# Generated by Django 2.0.1 on 2018-02-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Album')),
                ('type', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=30, verbose_name='Korean Name')),
                ('ename', models.CharField(blank=True, max_length=30, null=True, verbose_name='English Name')),
                ('debut_year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('belonged_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='song.Artist')),
            ],
            options={
                'ordering': ['kname', 'ename', 'type', 'debut_year'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('track_num', models.IntegerField(default=1)),
                ('disk_num', models.IntegerField(default=1)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Album')),
            ],
            options={
                'ordering': ['title', 'album'],
            },
        ),
        migrations.CreateModel(
            name='SongOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='song.SongOwnership', to='song.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'type', 'release_date')},
        ),
    ]
