# Generated by Django 2.0.1 on 2018-02-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
