# Generated by Django 2.0.1 on 2018-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180226_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['kname', 'ename', 'type', 'debut_year']},
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
    ]
