# Generated by Django 2.0.1 on 2018-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180226_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, default='South Korea', max_length=20, null=True),
        ),
    ]
